// Generated by CoffeeScript 1.4.0
(function() {
  var InputStream;

  InputStream = (function() {

    function InputStream(stream, descriptor, position) {
      this.stream = stream;
      this.descriptor = descriptor;
      this.position = position != null ? position : 0;
    }

    InputStream.prototype.read = function(length) {
      var buffer;
      buffer = new Buffer(length);
      this.position += this.stream.readSync(this.descriptor, buffer, 0, length, this.position);
      return buffer;
    };

    InputStream.prototype.readShort = function() {
      var buffer;
      buffer = this.read(2);
      return buffer[1] & 0xFF | (buffer[0] & 0xFF) << 8;
    };

    InputStream.prototype.readString = function(length) {
      if (length > 0) {
        return this.read(length).toString('UTF-8');
      }
    };

    InputStream.prototype.skip = function(length) {
      if (length == null) {
        length = 1;
      }
      if (length > 0) {
        return this.position += length;
      }
    };

    InputStream.prototype.readInt = function() {
      var buffer;
      buffer = this.read(4);
      return buffer[3] | (buffer[2] & 0xFF) << 8 | (buffer[1] & 0xFF) << 16 | (buffer[0] & 0xFF) << 24;
    };

    return InputStream;

  })();

  module.exports = InputStream;

}).call(this);
