// Generated by CoffeeScript 1.4.0
(function() {
  var Header;

  Header = (function() {

    function Header() {
      this.channels = 1;
      this.height = 1;
      this.width = 1;
      this.depth = 1;
      this.colorMode = 0;
    }

    return Header;

  })();

  module.exports = Header;

}).call(this);
