// Generated by CoffeeScript 1.4.0
(function() {
  var ImageResource;

  ImageResource = (function() {

    function ImageResource(length) {
      this.length = length != null ? length : 0;
      console.log("" + module.id + ": Image resources length is " + this.length);
    }

    return ImageResource;

  })();

  module.exports = ImageResource;

}).call(this);
