// Generated by CoffeeScript 1.4.0
(function() {
  var ImageResource, InputStream, Parser;

  ImageResource = require('./imageResource');

  InputStream = require('../../extensions/inputStream');

  Parser = (function() {

    function Parser(fileName, bufferPosition, callback) {
      this.fs = require('fs');
      this.parse(fileName, bufferPosition, callback);
    }

    Parser.prototype.parse = function(fileName, bufferPosition, callback) {
      var _this = this;
      return this.fs.open(fileName, 'r', '0666', function(err, fd) {
        var length, stream;
        if (err) {
          throw err;
        }
        stream = new InputStream(_this.fs, fd, bufferPosition);
        length = stream.readInt();
        _this.imageResource = new ImageResource(length);
        return callback(null, stream.position);
      });
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
