// Generated by CoffeeScript 1.4.0
(function() {
  var ColorMode;

  ColorMode = (function() {

    function ColorMode(colorData) {
      this.colorData = colorData;
    }

    return ColorMode;

  })();

  module.exports = ColorMode;

}).call(this);
