// Generated by CoffeeScript 1.4.0
(function() {
  var HeaderSpec, InputStream, Parser;

  HeaderSpec = require('../header/spec');

  InputStream = require('../../extensions/inputStream');

  Parser = (function() {

    function Parser(fileName, header, bufferPosition, callback) {
      this.fs = require('fs');
      this._colorMode = require('./colorMode');
      this.parse(fileName, header.colorMode, bufferPosition, callback);
    }

    Parser.prototype.parse = function(fileName, colorMode, bufferPosition, callback) {
      var _this = this;
      return this.fs.open(fileName, 'r', '0666', function(err, fd) {
        var colorData, stream;
        stream = new InputStream(_this.fs, fd, bufferPosition);
        if (colorMode === HeaderSpec.colorModes.Indexed) {
          colorData = stream.readString(768);
          _this._colorMode.colorData = colorData;
        } else if (colorMode === HeaderSpec.colorModes.Duotone) {
          console.log("Parsing duotone (" + colorMode + ") color mode.");
        } else {
          stream.skip(4);
        }
        return callback();
      });
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
